# Generated by Django 4.2 on 2024-08-02 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mov_home', '0009_alter_movie_year'),
        ('login_regis', '0002_ratemovie_userdislike_userlike_usermylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemovie',
            name='movie',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratemovie',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ratemovie',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='login_regis.userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdislike',
            name='movie',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdislike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdislike',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='login_regis.userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dislike',
            field=models.ManyToManyField(related_name='disliked_by', through='login_regis.UserDislike', to='mov_home.movie'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='like',
            field=models.ManyToManyField(related_name='liked_by', through='login_regis.UserLike', to='mov_home.movie'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mylist',
            field=models.ManyToManyField(related_name='mylist_for', through='login_regis.UserMyList', to='mov_home.movie'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.ManyToManyField(related_name='ratemovie_by', through='login_regis.RateMovie', to='mov_home.movie'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='watched',
            field=models.ManyToManyField(related_name='watched_by', through='login_regis.UserWatched', to='mov_home.movie'),
        ),
        migrations.AddField(
            model_name='userlike',
            name='movie',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='login_regis.userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermylist',
            name='movie',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermylist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermylist',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='login_regis.userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwatched',
            name='movie',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwatched',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwatched',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='login_regis.userinfo'),
            preserve_default=False,
        ),
    ]
