# Generated by Django 4.2.13 on 2024-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mov_home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="awards",
            new_name="oscars",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="imdbRating",
            new_name="rating",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdbID",
        ),
        migrations.AddField(
            model_name="movie",
            name="adult",
            field=models.BooleanField(default=False, null=True, verbose_name="Adult"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(default="2024-1-1", null=True),
        ),
    ]
