# Generated by Django 4.2.13 on 2024-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mov_home", "0002_rename_awards_movie_oscars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(default="2024-07-15", null=True),
        ),
    ]
