# Generated by Django 4.2.13 on 2024-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mov_home", "0003_alter_movie_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(default="2024-07-17", null=True),
        ),
    ]
