# Generated by Django 4.2 on 2024-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_home', '0009_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default='2024-09-21', null=True),
        ),
    ]
