# Generated by Django 4.2 on 2024-09-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mov_home', '0011_alter_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mov_home.movie')),
            ],
        ),
    ]
