# Generated by Django 4.2 on 2024-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_home', '0012_mostwatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default='2024-09-28', null=True),
        ),
    ]
